##server {
##    listen 80;
##    server_name doc.lzloyo.cn;
##    #return 404;
##    return 301 https://doc.lzloyo.cn$request_uri;
##}
#
server {
    server_name doc.lzloyo.cn;
    listen 80;
    #listen 443 ssl;
    #ssl_certificate /etc/letsencrypt/live/lzloyo.cn/fullchain.pem; # managed by Certbot
    #ssl_certificate_key /etc/letsencrypt/live/lzloyo.cn/privkey.pem; # managed by Certbot
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    root /var/www/docs;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    resolver 8.8.8.8 ipv6=off;
    client_max_body_size 50M;
    client_body_buffer_size 128k;

    # log files
    access_log /var/log/nginx/doc_access.log;
    error_log /var/log/nginx/doc_error.log;
#
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    #location / {
    #    rewrite ^(.*)$ /index.php last;
    #}

    #location /favicon.ico {
    #    root /var/www/FileManager;
    #}

    location ~ \.(php|phar)(/.*)?$ {
	    try_files $uri =404;
        fastcgi_split_path_info ^(.+\.(?:php|phar))(/.*)$;

        fastcgi_intercept_errors on;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_pass unix:/dev/shm/php-fpm.sock;
    }

    #location ~* \.(json|jpg|jpeg|png|gif|ico|css|js|pdf|mp3|mp4|woff|woff2|svg|ttf|eot)$ {
    #location /static {
        #root /var/www/FileManager;
    location ~* ^/static/(css|js|img|fonts)/.+.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt|swf|pdf|bmp|eot|svg|ttf|woff|woff2)$ {
        access_log off;
        expires max;
    }
}
